---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggflower

<!-- badges: start -->
<!-- badges: end -->

The goal of ggflower is to ...

## Installation

You can install the development version of ggflower from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("drbradford12/ggflower")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(ggplot2)
library(ggflower)
## basic example code
n <- 4
dframe <- data.frame(index = 1:n, y = n:1)

# don't do this - use polar coordinates
dframe |>
  ggplot(aes(x = index, y = y)) +
  geom_flower(aes(fill = factor(index)), shape="heart") 


dframe |>
  ggplot(aes(x = index, y = y)) +
  geom_flower(aes(fill = factor(index)), shape="heart") +
  coord_polar()


n <- 12
dframe <- data.frame(index = 1:n, y = abs(rnorm(n, mean=2)))

dframe |>
  ggplot(aes(x = index, y = y)) +
  geom_flower(aes(fill = y), shape="circle", colour = NA) +
  coord_polar() +
  theme_void() +
  scale_fill_gradient(low="yellow", high="darkorange")


n <- 12
k <- 9
dframe <- data.frame(
  expand.grid(
  index = 1:n, facet=1:k), y = abs(rnorm(n*k, mean=2)))

dframe |>
  ggplot(aes(x = index, y = y)) +
  geom_flower(shape="circle", aes(fill = y), colour=NA) +
  facet_wrap(~facet) +
  coord_polar() +
  theme_void() +
  scale_fill_gradient(low="yellow", high="darkorange") +
  theme(legend.position = "none")
```

